# Generated by Django 5.0.4 on 2024-05-01 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trellobackend', '0002_remove_columns_user_columns_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='title',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetic characters are allowed.')]),
        ),
    ]
